version: '3'
services:
  nginx:
    restart: always
    container_name: rp_redisinsight
    image: nginx:latest
    ports:
      - "8002:80"
    volumes:
      - ./nginx/conf:/etc/nginx/
      - ./nginx/logs:/var/log/nginx


  redisinsight:
    image: redisinsight
    container_name: redisinsight
    restart: always
    volumes:
      - ./redis_data:/db
      - ./redis_user_data:/root/.redisinsight-v2
    cap_add:
      - IPC_LOCK
